CREATE DATABASE pern_blog;

CREATE TABLE blog(
    post_id SERIAL PRIMARY KEY,
    title VARCHAR(255),
    content VARCHAR(255),
    author VARCHAR(255),
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);